-- =========================================================
-- EventPass - Esquema PostgreSQL (Supabase)
-- Compatible con entidades JPA actuales del proyecto.
-- =========================================================

-- ---------------------------------------------------------
-- Limpieza (solo para entorno de desarrollo/demo)
-- ---------------------------------------------------------
DROP TABLE IF EXISTS registros_acceso CASCADE;
DROP TABLE IF EXISTS entradas CASCADE;
DROP TABLE IF EXISTS evento_validadores CASCADE;
DROP TABLE IF EXISTS asistentes CASCADE;
DROP TABLE IF EXISTS eventos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

DROP TYPE IF EXISTS estado_pago CASCADE;
DROP TYPE IF EXISTS estado_entrada CASCADE;
DROP TYPE IF EXISTS estado_evento CASCADE;
DROP TYPE IF EXISTS rol_usuario CASCADE;

-- ---------------------------------------------------------
-- Tipos enum PostgreSQL
-- ---------------------------------------------------------
CREATE TYPE rol_usuario AS ENUM ('ADMIN', 'USUARIO', 'VALIDADOR');
CREATE TYPE estado_evento AS ENUM ('PLANIFICADO', 'PUBLICADO', 'CANCELADO', 'FINALIZADO');
CREATE TYPE estado_entrada AS ENUM ('ACTIVA', 'USADA', 'CANCELADA');
CREATE TYPE estado_pago AS ENUM ('PENDIENTE', 'PAGADO', 'CANCELADO');

-- ---------------------------------------------------------
-- Tabla: usuarios
-- ---------------------------------------------------------
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    contrasena_cifrada VARCHAR(255) NOT NULL,
    rol rol_usuario NOT NULL,
    creado_en TIMESTAMP NOT NULL
);

-- ---------------------------------------------------------
-- Tabla: eventos
-- ---------------------------------------------------------
CREATE TABLE eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT NOT NULL,
    imagen_url TEXT,
    ubicacion VARCHAR(180) NOT NULL,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    capacidad INTEGER NOT NULL,
    estado estado_evento NOT NULL,
    precio NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    creado_en TIMESTAMP NOT NULL,
    id_organizador BIGINT NOT NULL,

    CONSTRAINT fk_eventos_usuario_organizador
        FOREIGN KEY (id_organizador)
        REFERENCES usuarios(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ---------------------------------------------------------
-- Tabla: asistentes
-- Nota: tabla de asociación entre usuarios y eventos
-- ---------------------------------------------------------
CREATE TABLE asistentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registrado_en TIMESTAMP NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_evento BIGINT NOT NULL,

    CONSTRAINT fk_asistentes_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_asistentes_evento
        FOREIGN KEY (id_evento)
        REFERENCES eventos(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ---------------------------------------------------------
-- Tabla: evento_validadores
-- Nota: relación entre eventos y validadores
-- ---------------------------------------------------------
CREATE TABLE evento_validadores (
    id_evento BIGINT NOT NULL,
    id_validador BIGINT NOT NULL,
    PRIMARY KEY (id_evento, id_validador),

    CONSTRAINT fk_evento_validadores_evento
        FOREIGN KEY (id_evento)
        REFERENCES eventos(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_evento_validadores_validador
        FOREIGN KEY (id_validador)
        REFERENCES usuarios(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ---------------------------------------------------------
-- Tabla: entradas
-- ---------------------------------------------------------
CREATE TABLE entradas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qr_token VARCHAR(255) NOT NULL UNIQUE,
    estado estado_entrada NOT NULL,
    estado_pago estado_pago NOT NULL,
    comprada_en TIMESTAMP NOT NULL,
    usada_en TIMESTAMP NULL,
    id_asistente BIGINT NOT NULL,

    CONSTRAINT fk_entradas_asistente
        FOREIGN KEY (id_asistente)
        REFERENCES asistentes(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ---------------------------------------------------------
-- Tabla: registros_acceso
-- Nota: registro de accesos por validación de entradas
-- ---------------------------------------------------------
CREATE TABLE registros_acceso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_acceso TIMESTAMP NOT NULL,
    observaciones TEXT,
    id_entrada BIGINT NOT NULL,

    CONSTRAINT fk_registros_acceso_entrada
        FOREIGN KEY (id_entrada)
        REFERENCES entradas(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
